name: Lint
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-linter-action@main
      with:
        paths: |
          ./rtl  
        github_token: ${{ secrets.GITHUB_TOKEN }}
